version: "3.4"
services:
  web:
    image: "registry.gitlab.com/kasperix/java-with-spring-boot-server-with_db:deploy-remote-ssh_test.0.1"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    ports:
      - 5000:5000
    networks:
      - webnet
networks:
  webnet: